In [ ]:
import numpy as np
a = np.array ([[1,2,3,4],[5,6,7,8]])
a.shape , a.shape

b = np.arange(6), reshape (2,3)
b.shape


NameError: name 'reshape' is not defined

In [ ]:
import numpy as np
import random
from timeit import timeit

# Define addition functions
def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

# Generate larger random sample data
size = 100000  # Increased size for more pronounced difference
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)

# Time the execution of each function
python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"Pure Python addition: {python_time:.6f} seconds per loop")
print(f"NumPy addition: {numpy_time:.6f} seconds per loop")


Pure Python addition: 2.982305 seconds per loop
NumPy addition: 0.012158 seconds per loop


In [ ]:
import numpy as np

# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
import numpy as np

# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")


0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [ ]:
import numpy as np

# Using numpy's arange function
a = np.arange(1, 10)
print(a)

# Using Python's range function
x = range(1, 10)
print(x)  # x is an iterator
print(list(x))  # converting to list for display

# Further arange examples
x = np.arange(10.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)


[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
import numpy as np

# Create an array
array = np.array([1, 2, 3])

# Multiply each element by 2
new_array = array * 2

# Copy the array
copied_array = np.copy(array)

# Slice the array from index 1 to 2
sliced_array = array[1:2]

# Print results
print("Original array:", array)
print("Array multiplied by 2:", new_array)
print("Copied array:", copied_array)
print("Sliced array:", sliced_array)


Original array: [1 2 3]
Array multiplied by 2: [2 4 6]
Copied array: [1 2 3]
Sliced array: [2]


In [ ]:
import numpy as np

# Create two 2x2 arrays
arr1 = np.array([[1, 2], [3, 4]])   # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]])   # Shape: (2, 2)

# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6]
#                 [3 4 7 8]]

vstacked = np.vstack((arr1, arr2))
# Output vstack: [[1 2]
#                 [3 4]
#                 [5 6]
#                 [7 8]]

colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5]
#                       [2 6]]

print(hstacked)
print(vstacked)
print(colstacked)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


worksheet 1

task 1

In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array:\n", empty_array)

# Task 2: Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-one array:\n", ones_array)

# Task 3: Return a new array filled with a specific value
filled_array = np.full((3, 3), 7)  # Shape 3x3, filled with 7
print("\nFilled array:\n", filled_array)

# Task 4: Return a zeros array with the same shape as another array
base_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(base_array)
print("\nZeros array like base array:\n", zeros_like_array)

# Task 5: Return a ones array with the same shape as another array
ones_like_array = np.ones_like(base_array)
print("\nOnes array like base array:\n", ones_like_array)

# Task 6: Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nConverted NumPy array:\n", array_from_list)


Empty array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

All-one array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array like base array:
 [[0 0]
 [0 0]]

Ones array like base array:
 [[1 1]
 [1 1]]

Converted NumPy array:
 [1 2 3 4]


task 2

In [ ]:
# Task 1: Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", range_array)

# Task 2: Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix:\n", matrix_3x3)

# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

# Task 4: Create a random array of size 30 and find the mean
random_array = np.random.random(30)
print("\nMean of random array:", random_array.mean())

# Task 5: Create a 10x10 array with random values and find min and max
large_random_array = np.random.random((10, 10))
print("\nMinimum value:", large_random_array.min())
print("Maximum value:", large_random_array.max())

# Task 6: Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nModified zero array:\n", zero_array)

# Task 7: Reverse an array
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("\nReversed array:\n", reversed_array)

# Task 8: Create a 2D array with 1 on border and 0 inside
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
print("\n2D array with border of 1s:\n", bordered_array)

# Task 9: Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard pattern:\n", checkerboard)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array: 0.37930451693770556

Minimum value: 0.0014245617310507663
Maximum value: 0.9646528833427859

Modified zero array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
 [0, 4, 0, 0, 2, 1]

2D array with border of 1s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


task 3

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
print("Addition:\n", x + y)

# Task 2: Subtract the two arrays
print("\nSubtraction:\n", x - y)

# Task 3: Multiply the array with a scalar
print("\nMultiplication by 3:\n", x * 3)

# Task 4: Find the square of each element
print("\nSquare of each element:\n", np.square(x))

# Task 5: Dot product
print("\nDot product (v and w):", np.dot(v, w))
print("Dot product (x and v):\n", np.dot(x, v))
print("Dot product (x and y):\n", np.dot(x, y))

# Task 6: Concatenate x and y along row and v and w along column
print("\nConcatenate x and y along row:\n", np.vstack((x, y)))
print("Concatenate v and w along column:\n", np.column_stack((v, w)))

# Task 7: Concatenate x and v
try:
    print("\nConcatenate x and v:\n", np.concatenate((x, v), axis=0))
except ValueError as e:
    print("\nError encountered:", e)
    print("Explanation: The dimensions of x and v are incompatible for concatenation along rows.")


Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiplication by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element:
 [[ 1  4]
 [ 9 25]]

Dot product (v and w): 219
Dot product (x and v):
 [29 77]
Dot product (x and y):
 [[19 22]
 [50 58]]

Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

Error encountered: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The dimensions of x and v are incompatible for concatenation along rows.


task 4

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)
identity_proof = np.dot(A, A_inv)
print("A.A^(-1) = I:\n", identity_proof)

# Task 2: Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# Task 3: Prove (AB)^T = B^T A^T
print("\n(AB)^T:\n", AB.T)
print("B^T A^T:\n", np.dot(B.T, A.T))

# Task 4: Solve the system of equations using the inverse method
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
solutions = np.linalg.solve(coefficients, constants)
print("\nSolutions to the system of equations:\n", solutions)


A.A^(-1) = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]

Solutions to the system of equations:
 [ 2.  1. -2.]


task 5

In [ ]:
import time

# Element-wise addition
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))
start = time.time()
list_result = [a + b for a, b in zip(list1, list2)]
print("List addition time:", time.time() - start)

np_array1 = np.array(list1)
np_array2 = np.array(list2)
start = time.time()
np_result = np_array1 + np_array2
print("NumPy addition time:", time.time() - start)

# Element-wise multiplication
start = time.time()
list_result = [a * b for a, b in zip(list1, list2)]
print("\nList multiplication time:", time.time() - start)

start = time.time()
np_result = np_array1 * np_array2
print("NumPy multiplication time:", time.time() - start)

# Dot product
start = time.time()
dot_result = sum(a * b for a, b in zip(list1, list2))
print("\nList dot product time:", time.time() - start)

start = time.time()
np_dot_result = np.dot(np_array1, np_array2)
print("NumPy dot product time:", time.time() - start)

# Matrix multiplication
matrix1 = [[1] * 1000 for _ in range(1000)]
matrix2 = [[1] * 1000 for _ in range(1000)]
start = time.time()
result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
print("\nList matrix multiplication time:", time.time() - start)

np_matrix1 = np.ones((1000, 1000))
np_matrix2 = np.ones((1000, 1000))
start = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
print("NumPy matrix multiplication time:", time.time() - start)


List addition time: 0.11145758628845215
NumPy addition time: 0.005076169967651367

List multiplication time: 0.1029806137084961
NumPy multiplication time: 0.005317211151123047

List dot product time: 0.11453628540039062
NumPy dot product time: 0.0020215511322021484

List matrix multiplication time: 118.70503616333008
NumPy matrix multiplication time: 0.10613012313842773


In [ ]:
# Task 1: Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", range_array)

# Task 2: Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix:\n", matrix_3x3)

# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Task 5: Create a 10x10 array with random values and find min and max
large_random_array = np.random.random((10, 10))
print("\nMinimum value:", large_random_array.min())
print("Maximum value:", large_random_array.max())

# Task 6: Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nModified zero array:\n", zero_array)

# Task 7: Reverse an array
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("\nReversed array:\n", reversed_array)


Minimum value: 0.009199930959144731
Maximum value: 0.992941718593039

Modified zero array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
 [0, 4, 0, 0, 2, 1]


In [ ]:
# Task 7: Reverse an array
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("\nReversed array:\n", reversed_array)

# Task 8: Create a 2D array with 1 on border and 0 inside
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
print("\n2D array with border of 1s:\n", bordered_array)

# Task 9: Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard pattern:\n", checkerboard)


Reversed array:
 [0, 4, 0, 0, 2, 1]

2D array with border of 1s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
print("Addition:\n", x + y)

# Task 2: Subtract the two arrays
print("\nSubtraction:\n", x - y)

# Task 3: Multiply the array with a scalar
print("\nMultiplication by 5:\n", x * 5)

# Task 4: Find the square of each element
print("\nSquare of each element:\n", np.square(x))

# Task 5: Dot product
print("\nDot product (v and w):", np.dot(v, w))
print("Dot product (x and v):\n", np.dot(x, v))
print("Dot product (x and y):\n", np.dot(x, y))

# Task 6: Concatenate x and y along row and v and w along column
print("\nConcatenate x and y along row:\n", np.vstack((x, y)))
print("Concatenate v and w along column:\n", np.column_stack((v, w)))




Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiplication by 5:
 [[ 5 10]
 [15 25]]

Square of each element:
 [[ 1  4]
 [ 9 25]]

Dot product (v and w): 219
Dot product (x and v):
 [29 77]
Dot product (x and y):
 [[19 22]
 [50 58]]

Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]
